"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const admin_1 = __importDefault(require("./admin"));
const filter_1 = __importDefault(require("./filter"));
const guideline_1 = __importDefault(require("./guideline"));
const image_1 = __importDefault(require("./image"));
const product_1 = __importDefault(require("./product"));
const user_1 = __importDefault(require("./user"));
const search_1 = __importDefault(require("./search"));
const router = express_1.default.Router();
router.use('/admin', admin_1.default);
router.use('/filter', filter_1.default);
router.use('/guideline', guideline_1.default);
router.use('/image', image_1.default);
router.use('/product', product_1.default);
router.use('/user', user_1.default);
router.use('/search', search_1.default);
exports.default = router;
